"""
Automated Test Suite for Anti-Hallucination Protection (Phase 2).
Verifies that claims without source evidence are rejected, flagged for review, and not presented as facts.
"""

import sys
import os
import unittest

sys.path.insert(0, os.path.abspath("."))

from backend.models import (
    SpecificationAttribute, MatchStatus, EvidenceType, SourceReliability
)
from backend.evidence import isolate_evidence_record
from backend.confidence import calculate_attribute_confidence
from backend.explainability import generate_attribute_explainability


class TestAntiHallucination(unittest.TestCase):

    def test_01_reject_hallucinated_attributes(self):
        """Test rejection of attributes generated by LLM that do not exist in source text."""
        source_pages = [
            {"page": 1, "text": "Industrial Temperature Sensor TS-200. Operating Range: -50 to 200 °C. Probe: 100 mm."}
        ]

        # 1. Hallucinated Warranty Period
        ev_warranty = isolate_evidence_record(
            attr_name="Warranty Period",
            raw_val_str="3 years",
            normalized_val_str="3",
            unit_str="years",
            raw_pages=source_pages
        )

        self.assertEqual(ev_warranty.match_status, MatchStatus.NOT_FOUND)
        self.assertEqual(ev_warranty.evidence_type, EvidenceType.UNVERIFIED)
        self.assertEqual(ev_warranty.evidence_confidence, 0.0)

        conf = calculate_attribute_confidence(
            val_str="3",
            unit_str="years",
            match_status=ev_warranty.match_status,
            evidence_score=ev_warranty.evidence_confidence
        )
        self.assertEqual(conf, 0)

        spec = SpecificationAttribute(
            name="Warranty Period",
            value="3",
            unit="years",
            match_status=ev_warranty.match_status,
            evidence_type=ev_warranty.evidence_type,
            confidence=conf,
            status="UNVERIFIED"
        )
        exp = generate_attribute_explainability(spec)

        self.assertTrue(exp.review_required)
        self.assertEqual(exp.final_status, "UNVERIFIED")
        self.assertIn("Evidence was not found", exp.review_reason)

    def test_02_verified_attribute_accepted_cleanly(self):
        """Test that source-backed attributes pass without hallucination flags."""
        source_pages = [
            {"page": 1, "text": "Industrial Temperature Sensor TS-200. Operating Range: -50 to 200 °C. Probe: 100 mm."}
        ]

        ev_temp = isolate_evidence_record(
            attr_name="Operating Range",
            raw_val_str="-50 to 200",
            normalized_val_str="-50 to 200",
            unit_str="°C",
            raw_pages=source_pages
        )

        self.assertEqual(ev_temp.match_status, MatchStatus.VERIFIED)
        self.assertGreaterEqual(ev_temp.evidence_confidence, 0.90)

        conf = calculate_attribute_confidence(
            val_str="-50 to 200",
            unit_str="°C",
            page_num=1,
            evidence_snippet=ev_temp.quote,
            evidence_score=ev_temp.evidence_confidence,
            match_status=ev_temp.match_status
        )
        self.assertGreaterEqual(conf, 90)


if __name__ == "__main__":
    unittest.main()
