import threading
from typing import List

from backend.ingestion.models import SourceDocument

class _ProductState:
    """Thread‑safe singleton to hold the current ingestion session state.
    It tracks whether multi‑source mode is enabled and stores provenance
    ``SourceDocument`` objects for the current product analysis.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._multi_source: bool = False
        self._sources: List[SourceDocument] = []

    # -------------------------------
    # Public API used by FastAPI handlers
    # -------------------------------
    def reset(self) -> None:
        """Clear all stored sources and disable multi‑source mode.
        Called at the start of a single‑source request to ensure a clean
        state.
        """
        with self._lock:
            self._sources.clear()
            self._multi_source = False

    def enable_multi_source(self) -> None:
        """Enable multi‑source mode for the current request.
        When enabled, subsequent ``add_sources`` calls will *append* rather
        than replace the existing provenance list.
        """
        with self._lock:
            self._multi_source = True

    def is_multi_source(self) -> bool:
        """Return ``True`` if multi‑source mode is currently active."""
        with self._lock:
            return self._multi_source

    def add_sources(self, new_sources: List[SourceDocument], replace: bool = True) -> None:
        """Add provenance ``SourceDocument`` objects to the current state.

        Parameters
        ----------
        new_sources:
            List of ``SourceDocument`` instances generated by the ingestion
            adapters.
        replace:
            When ``True`` (default) the previous source list is discarded.
            When ``False`` the new sources are appended – this is the
            behaviour used for multi‑source requests.
        """
        with self._lock:
            if replace:
                self._sources = list(new_sources)
            else:
                # Preserve existing order while appending new items
                self._sources.extend(new_sources)

    def get_sources(self) -> List[SourceDocument]:
        """Return a copy of the current source list for inspection."""
        with self._lock:
            return list(self._sources)

# Export a module‑level singleton used throughout the codebase.
product_state = _ProductState()
